{
  "data": {
    "id": 1613,
    "exerciseKey": "023f27d0-f90b-446d-bd6c-293e95f9c9b8",
    "category": "QA",
    "renderType": "md",
    "title": "【Promise第21题】下面代码的输出是什么？",
    "desc": "```js\nPromise.reject('err!!!')\n  .then((res) => {\n    console.log('success', res)\n  }, (err) => {\n    console.log('error', err)\n  }).catch(err => {\n    console.log('catch', err)\n  })\n\n```",
    "options": null,
    "explanation": "## 解析\n\n.then函数中的两个参数。\n\n第一个参数是用来处理Promise成功的函数，第二个则是处理失败的函数。\n\n也就是说Promise.resolve('xxx')的值会进入成功的函数，Promise.reject('xxx')的值会进入失败的函数。\n\n## 答案\n```\n'error' 'err!!!'\n```",
    "level": 3,
    "status": 2,
    "appId": 7,
    "createAt": "2022-01-09T14:51:25.000Z",
    "updateAt": "2023-03-26T08:41:30.000Z",
    "updateUserId": 11,
    "isCollected": false,
    "currentIndex": 412,
    "prev": "75022926-8fe3-4f93-bab2-4e3c8e31c170",
    "next": "637b0af3-e1e1-42c0-9825-e34aa0a4e4a0"
  },
  "post": {
    "exerciseKey": "023f27d0-f90b-446d-bd6c-293e95f9c9b8",
    "category": "QA",
    "title": "【Promise第21题】下面代码的输出是什么？",
    "level": 3,
    "updateAt": "2023-03-26T08:41:30+00:00"
  },
  "tag": {
    "id": 10,
    "tagName": "JavaScript",
    "type": "1",
    "exerciseCount": 322
  }
}