---
title: 【Promise第21题】下面代码的输出是什么？
pubDatetime: 2023-03-26T08:41:30.000Z
author: caorushizi
tags:
  - JavaScript
postSlug: 023f27d0-f90b-446d-bd6c-293e95f9c9b8
description: >-
  Promise.reject('err!!!') .then((res) => { console.log('success', res) }, (err)
  => { console.log('error', err) }).catch(err => { console.log('catch', err) })
  解析 .then函数中的两个参数。 第一个参数是用来处理Promise成功的函数，第二
difficulty: 3
questionNumber: 1613
source: https://fe.ecool.fun/topic/023f27d0-f90b-446d-bd6c-293e95f9c9b8
---

```js
Promise.reject("err!!!")
  .then(
    res => {
      console.log("success", res);
    },
    err => {
      console.log("error", err);
    }
  )
  .catch(err => {
    console.log("catch", err);
  });
```

---

## 解析

.then 函数中的两个参数。

第一个参数是用来处理 Promise 成功的函数，第二个则是处理失败的函数。

也就是说 Promise.resolve('xxx')的值会进入成功的函数，Promise.reject('xxx')的值会进入失败的函数。

## 答案

```
'error' 'err!!!'
```
